name: NetherRatio
version: '1.0'
main: org.doraji.nethercorrespondence.Nethercorrespondence
api-version: '1.21'
commands:
  netherratio:
    description: 네더의 비율을 설정합니다.
    usage: /netherratio [<ratio>]
    permission: nethercorrespondence.netherratio

permissions:
  nethercorrespondence.netherratio:
    description: Allows changing the nether-overworld ratio
    default: op
