name: NetherRatio
version: '2.0.2'
main: org.doraji.nethercorrespondence.Nethercorrespondence
api-version: '1.21'
commands:
  netherratio:
    description: Manage nether-overworld ratios and calculate portal coordinates.
    usage: |
      /netherratio - List all ratios
      /netherratio list - List all ratios
      /netherratio set <ratio> - Set default ratio
      /netherratio set <ratio> <world> - Set ratio for specific world
      /netherratio calc - Calculate coordinates at your position
      /netherratio calc <x> <z> - Calculate coordinates
      /netherratio reload - Reload configuration
    permission: nethercorrespondence.netherratio

permissions:
  nethercorrespondence.netherratio:
    description: Allows changing the nether-overworld ratio
    default: op
  nethercorrespondence.calc:
    description: Allows using the portal coordinate calculator
    default: true
