name: NetherRatio
version: '2.0.0'
main: org.doraji.nethercorrespondence.Nethercorrespondence
api-version: '2.0.0'
commands:
  netherratio:
    description: Sets the nether-overworld ratio.
    usage: /netherratio [<ratio>]
    permission: nethercorrespondence.netherratio

permissions:
  nethercorrespondence.netherratio:
    description: Allows changing the nether-overworld ratio
    default: op
